/* Auto-generated by tools/gen_compressor.py. Do not edit by hand. */
/*
 * Dynamic compressor gain table contract
 *
 * Compressor input range: [-1024, 1023]
 * 0 dBFS: abs(input) == 1024
 * Output range before PWM offset: [-127, 127]
 * Output full-scale magnitude: 127
 * Envelope index scale: env = min(abs(raw_mixOut) >> 2, 255)
 *
 * For each table entry env:
 *   mag = env << 2
 *   in_db = 20 * log10(mag / 1024)
 *   if in_db <= -6.0:
 *       out_db = in_db
 *   else:
 *       out_db = -6.0 + (in_db - (-6.0)) / 4.0
 *   out_db += 4.5
 *   target = 127 * 10^(out_db / 20)
 *   gain_q8 = round(target * 256 / mag)
 *
 * env == 0 uses the nominal pass-through gain instead of dividing by zero.
 * The generated table is forced monotonic non-increasing to avoid gain jitter.
 */
#ifndef SYNTH_COMPRESSOR_GENERATED_H
#define SYNTH_COMPRESSOR_GENERATED_H

#include <stdint.h>

#define SYNTH_COMPRESSOR_INPUT_MIN (-1024)
#define SYNTH_COMPRESSOR_INPUT_MAX (1023)
#define SYNTH_COMPRESSOR_OUTPUT_MIN (-127)
#define SYNTH_COMPRESSOR_OUTPUT_MAX (127)
#define SYNTH_COMPRESSOR_ENV_SHIFT 2
#define SYNTH_COMPRESSOR_FAST_GAIN 53

extern const __code uint8_t SynthCompressorGainTable[256];

#endif
