#!/usr/bin/env python3
"""Generate dynamic dBFS compressor tables for the 8051 synth."""

from __future__ import annotations

import argparse
from math import log10, pow
from pathlib import Path


def clamp(v: float, lo: float, hi: float) -> float:
    return min(max(v, lo), hi)


def compressed_db_at_full_scale(threshold_db: float, ratio: float) -> float:
    return threshold_db + (0.0 - threshold_db) / ratio


def resolve_compressor_params(args: argparse.Namespace) -> None:
    if args.threshold_db is None:
        args.threshold_db = -6.0
    if args.ratio is None:
        args.ratio = 4.0
    if args.ratio < 1.0:
        raise ValueError("ratio must be >= 1.0")

    if args.makeup_db is not None:
        return
    if args.preset == "safe":
        args.makeup_db = 0.0
    elif args.preset == "loud":
        args.makeup_db = -compressed_db_at_full_scale(args.threshold_db, args.ratio)
    else:
        args.makeup_db = 0.0


def target_magnitude(
    mag: int,
    input_full_scale: int,
    output_full_scale: int,
    threshold_db: float,
    ratio: float,
    makeup_db: float,
) -> float:
    if mag == 0:
        return 0.0

    in_db = 20.0 * log10(mag / input_full_scale)
    if in_db <= threshold_db:
        out_db = in_db
    else:
        out_db = threshold_db + (in_db - threshold_db) / ratio
    out_db += makeup_db

    y = output_full_scale * pow(10.0, out_db / 20.0)
    return clamp(y, 0.0, output_full_scale)


def derive_ranges(args: argparse.Namespace) -> tuple[int, int, int, int, int, int]:
    if args.input_bits < 2:
        raise ValueError("input-bits must be at least 2")
    if args.output_bits < 2 and (args.output_min is None or args.output_max is None):
        raise ValueError("output-bits must be at least 2 when output range is not explicit")

    input_full_scale = 1 << (args.input_bits - 1)
    input_min = -input_full_scale
    input_max = input_full_scale - 1

    if args.output_min is None and args.output_max is None:
        output_max = (1 << (args.output_bits - 1)) - 1
        output_min = -output_max
    elif args.output_min is not None and args.output_max is not None:
        output_min = args.output_min
        output_max = args.output_max
    else:
        raise ValueError("output-min and output-max must be specified together")

    if output_min >= 0 or output_max <= 0:
        raise ValueError("output range must cross zero")
    output_full_scale = min(-output_min, output_max)
    if output_full_scale < 1:
        raise ValueError("output range is too small")

    return input_min, input_max, input_full_scale, output_min, output_max, output_full_scale


def env_shift_for_input_bits(input_bits: int) -> int:
    return max(0, input_bits - 9)


def build_gain_table(args: argparse.Namespace, input_full_scale: int, output_full_scale: int) -> list[int]:
    table: list[int] = []
    env_shift = env_shift_for_input_bits(args.input_bits)
    makeup_gain = pow(10.0, args.makeup_db / 20.0)
    nominal_gain = round(output_full_scale * 256.0 * makeup_gain / input_full_scale)

    for env in range(256):
        mag = env << env_shift
        if mag == 0:
            gain = nominal_gain
        else:
            target = target_magnitude(
                mag,
                input_full_scale,
                output_full_scale,
                args.threshold_db,
                args.ratio,
                args.makeup_db,
            )
            gain = round(target * 256.0 / mag)
        table.append(max(0, min(255, int(gain))))

    for i in range(1, len(table)):
        if table[i] > table[i - 1]:
            table[i] = table[i - 1]
    return table


def emit_header(args: argparse.Namespace, input_min: int, input_max: int,
                input_full_scale: int, output_min: int, output_max: int,
                output_full_scale: int, gain_table: list[int]) -> str:
    lines: list[str] = []
    lines.append("/* Auto-generated by tools/gen_compressor.py. Do not edit by hand. */")
    lines.append("/*")
    lines.append(" * Dynamic compressor gain table contract")
    lines.append(" *")
    lines.append(f" * Compressor input range: [{input_min}, {input_max}]")
    lines.append(f" * 0 dBFS: abs(input) == {input_full_scale}")
    lines.append(f" * Output range before PWM offset: [{output_min}, {output_max}]")
    lines.append(f" * Output full-scale magnitude: {output_full_scale}")
    lines.append(f" * Envelope index scale: env = min(abs(raw_mixOut) >> {env_shift_for_input_bits(args.input_bits)}, 255)")
    lines.append(" *")
    lines.append(" * For each table entry env:")
    lines.append(f" *   mag = env << {env_shift_for_input_bits(args.input_bits)}")
    lines.append(f" *   in_db = 20 * log10(mag / {input_full_scale})")
    lines.append(f" *   if in_db <= {args.threshold_db}:")
    lines.append(" *       out_db = in_db")
    lines.append(" *   else:")
    lines.append(f" *       out_db = {args.threshold_db} + (in_db - ({args.threshold_db})) / {args.ratio}")
    lines.append(f" *   out_db += {args.makeup_db}")
    lines.append(f" *   target = {output_full_scale} * 10^(out_db / 20)")
    lines.append(" *   gain_q8 = round(target * 256 / mag)")
    lines.append(" *")
    lines.append(" * env == 0 uses the nominal pass-through gain instead of dividing by zero.")
    lines.append(" * The generated table is forced monotonic non-increasing to avoid gain jitter.")
    lines.append(" */")
    lines.append("#ifndef SYNTH_COMPRESSOR_GENERATED_H")
    lines.append("#define SYNTH_COMPRESSOR_GENERATED_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define SYNTH_COMPRESSOR_INPUT_MIN ({input_min})")
    lines.append(f"#define SYNTH_COMPRESSOR_INPUT_MAX ({input_max})")
    lines.append(f"#define SYNTH_COMPRESSOR_OUTPUT_MIN ({output_min})")
    lines.append(f"#define SYNTH_COMPRESSOR_OUTPUT_MAX ({output_max})")
    lines.append(f"#define SYNTH_COMPRESSOR_ENV_SHIFT {env_shift_for_input_bits(args.input_bits)}")
    lines.append(f"#define SYNTH_COMPRESSOR_FAST_GAIN {gain_table[0]}")
    lines.append("")
    lines.append("extern const __code uint8_t SynthCompressorGainTable[256];")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def emit_source(gain_table: list[int]) -> str:
    lines: list[str] = []
    lines.append("/* Auto-generated by tools/gen_compressor.py. Do not edit by hand. */")
    lines.append('#include "CompressorGenerated.h"')
    lines.append("")
    lines.append("const __code uint8_t SynthCompressorGainTable[256] = {")
    for i in range(0, len(gain_table), 16):
        lines.append("\t" + ", ".join(str(v) for v in gain_table[i:i + 16]) + ",")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-bits", type=int, default=11)
    parser.add_argument("--output-bits", type=int, default=8)
    parser.add_argument("--output-min", type=int)
    parser.add_argument("--output-max", type=int)
    parser.add_argument("--preset", choices=("safe", "loud", "custom"), default="loud")
    parser.add_argument("--threshold-db", type=float)
    parser.add_argument("--ratio", type=float)
    parser.add_argument("--makeup-db", type=float)
    parser.add_argument("--out-header", type=Path, default=Path("Synthesizer/CompressorGenerated.h"))
    parser.add_argument("--out-source", type=Path, default=Path("Synthesizer/CompressorGenerated.c"))
    args = parser.parse_args()

    resolve_compressor_params(args)
    input_min, input_max, input_full_scale, output_min, output_max, output_full_scale = derive_ranges(args)
    gain_table = build_gain_table(args, input_full_scale, output_full_scale)

    args.out_header.write_text(
        emit_header(args, input_min, input_max, input_full_scale, output_min, output_max,
                    output_full_scale, gain_table),
        encoding="ascii",
    )
    args.out_source.write_text(emit_source(gain_table), encoding="ascii")

    print(
        f"generated compressor gain table, input=[{input_min},{input_max}], "
        f"output=[{output_min},{output_max}], env_shift={env_shift_for_input_bits(args.input_bits)}, "
        f"fast_gain={gain_table[0]}"
    )


if __name__ == "__main__":
    main()
